// <auto-generated />
using System;
using Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20260129123309_AddIsBlockedToUser")]
    partial class AddIsBlockedToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Tin công nghệ",
                            Name = "Công nghệ"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Tin giải trí",
                            Name = "Giải trí"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Tin thể thao",
                            Name = "Thể thao"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Tin giáo dục",
                            Name = "Giáo dục"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Tin kinh tế",
                            Name = "Kinh tế"
                        });
                });

            modelBuilder.Entity("Blog.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            Content = "Bài hay",
                            CreatedAt = new DateTime(2026, 1, 29, 19, 33, 9, 63, DateTimeKind.Local).AddTicks(3500),
                            PostId = 1,
                            UserId = 4
                        },
                        new
                        {
                            CommentId = 2,
                            Content = "Rất hữu ích",
                            CreatedAt = new DateTime(2026, 1, 29, 19, 33, 9, 63, DateTimeKind.Local).AddTicks(3502),
                            PostId = 1,
                            UserId = 5
                        },
                        new
                        {
                            CommentId = 3,
                            Content = "Hay quá",
                            CreatedAt = new DateTime(2026, 1, 29, 19, 33, 9, 63, DateTimeKind.Local).AddTicks(3503),
                            PostId = 2,
                            UserId = 4
                        },
                        new
                        {
                            CommentId = 4,
                            Content = "Cảm ơn tác giả",
                            CreatedAt = new DateTime(2026, 1, 29, 19, 33, 9, 63, DateTimeKind.Local).AddTicks(3504),
                            PostId = 3,
                            UserId = 5
                        },
                        new
                        {
                            CommentId = 5,
                            Content = "Đọc rất thích",
                            CreatedAt = new DateTime(2026, 1, 29, 19, 33, 9, 63, DateTimeKind.Local).AddTicks(3505),
                            PostId = 4,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Blog.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Công khai");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            AuthorId = 2,
                            CategoryId = 1,
                            Content = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                            CreatedAt = new DateTime(2026, 1, 29, 19, 33, 9, 63, DateTimeKind.Local).AddTicks(3460),
                            Status = "Công khai",
                            Title = "Bài viết công nghệ",
                            Views = 10
                        },
                        new
                        {
                            PostId = 2,
                            AuthorId = 2,
                            CategoryId = 2,
                            Content = "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
                            CreatedAt = new DateTime(2026, 1, 29, 19, 33, 9, 63, DateTimeKind.Local).AddTicks(3480),
                            Status = "Công khai",
                            Title = "Bài viết giải trí",
                            Views = 5
                        },
                        new
                        {
                            PostId = 3,
                            AuthorId = 3,
                            CategoryId = 3,
                            Content = "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                            CreatedAt = new DateTime(2026, 1, 29, 19, 33, 9, 63, DateTimeKind.Local).AddTicks(3482),
                            Status = "Công khai",
                            Title = "Bài viết thể thao",
                            Views = 20
                        },
                        new
                        {
                            PostId = 4,
                            AuthorId = 3,
                            CategoryId = 4,
                            Content = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
                            CreatedAt = new DateTime(2026, 1, 29, 19, 33, 9, 63, DateTimeKind.Local).AddTicks(3484),
                            Status = "Công khai",
                            Title = "Bài viết giáo dục",
                            Views = 7
                        },
                        new
                        {
                            PostId = 5,
                            AuthorId = 2,
                            CategoryId = 5,
                            Content = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
                            CreatedAt = new DateTime(2026, 1, 29, 19, 33, 9, 63, DateTimeKind.Local).AddTicks(3485),
                            Status = "Công khai",
                            Title = "Bài viết kinh tế",
                            Views = 15
                        });
                });

            modelBuilder.Entity("Blog.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Reader");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            IsBlocked = false,
                            IsLocked = false,
                            Password = "123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "editor1@gmail.com",
                            FullName = "Editor One",
                            IsBlocked = false,
                            IsLocked = false,
                            Password = "123",
                            Role = "Editor",
                            Username = "editor1"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "editor2@gmail.com",
                            FullName = "Editor Two",
                            IsBlocked = false,
                            IsLocked = false,
                            Password = "123",
                            Role = "Editor",
                            Username = "editor2"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "reader1@gmail.com",
                            FullName = "Reader One",
                            IsBlocked = false,
                            IsLocked = false,
                            Password = "123",
                            Role = "Reader",
                            Username = "reader1"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "reader2@gmail.com",
                            FullName = "Reader Two",
                            IsBlocked = false,
                            IsLocked = false,
                            Password = "123",
                            Role = "Reader",
                            Username = "reader2"
                        });
                });

            modelBuilder.Entity("Blog.Models.Comment", b =>
                {
                    b.HasOne("Blog.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blog.Models.Post", b =>
                {
                    b.HasOne("Blog.Models.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Blog.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Blog.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Blog.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
